#!/bin/sh
exec tail -n +3 $0
# Isolated fixed-point classifier trial. Phase 63 and the safe 7.1.3 entry
# remain untouched.

menuentry 'Ubuntu SP11 7.1.1 Touch Phase 64 Fixed-Point Classifier' --id 'sp11-phase64' --class ubuntu --class gnu-linux --class gnu --class os {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod ext2
	insmod fdt
	search --no-floppy --fs-uuid --set=root 33e842b7-0434-4749-b03a-299bdcdb8b9f
	devicetree /boot/sp11-7.1.1-phase64/sp11-7.1.1-phase64-hybrid.dtb
	linux /boot/sp11-7.1.1-phase64/vmlinuz-7.1.1-sp11-gpicmp1+ root=UUID=33e842b7-0434-4749-b03a-299bdcdb8b9f ro clk_ignore_unused pd_ignore_unused cma=128M efi=noruntime quiet splash console=tty0 crashkernel=2G-4G:320M,4G-32G:512M,32G-64G:1024M,64G-128G:2048M,128G-:4096M sp11_entry=7.1.1-phase64
	initrd /boot/sp11-7.1.1-phase64/initrd.img-7.1.1-sp11-gpicmp1+-phase64
}
