#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
exec tail -n +4 $0
# Phase 68 retains the Phase 67 hardening but restores the hardware-proven
# minimal cold-start and reset-recovery sequence.

menuentry 'Ubuntu SP11 7.1.1 Touch Phase 68 Proven Recovery' --id 'sp11-phase68' --class ubuntu --class gnu-linux --class gnu --class os {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod ext2
	insmod fdt
	search --no-floppy --fs-uuid --set=root 33e842b7-0434-4749-b03a-299bdcdb8b9f
	devicetree /boot/sp11-7.1.1-phase68/sp11-7.1.1-phase68-hybrid.dtb
	linux /boot/sp11-7.1.1-phase68/vmlinuz-7.1.1-sp11-gpicmp1+ root=UUID=33e842b7-0434-4749-b03a-299bdcdb8b9f ro clk_ignore_unused pd_ignore_unused cma=128M efi=noruntime quiet splash console=tty0 crashkernel=2G-4G:320M,4G-32G:512M,32G-64G:1024M,64G-128G:2048M,128G-:4096M sp11_entry=7.1.1-phase68
	initrd /boot/sp11-7.1.1-phase68/initrd.img-7.1.1-sp11-gpicmp1+-phase68
}
