#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
exec tail -n +4 $0
# Phase 84 is an input-disabled Windows cold-init parity checkpoint. It uses
# the captured provider state from this exact SP11 and stops before CFU/Heat.

menuentry 'Ubuntu SP11 7.1.3 Windows Init Parity, No Touch (Phase 84)' --id 'sp11-phase84-init-parity' --class ubuntu --class gnu-linux --class gnu --class os {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_gpt
        insmod ext2
        insmod fdt
        search --no-floppy --fs-uuid --set=root 33e842b7-0434-4749-b03a-299bdcdb8b9f
        devicetree /boot/sp11-7.1.3-phase84-init-parity/x1e80100-microsoft-denali-sp11-phase75.dtb
        linux /boot/sp11-7.1.3-phase84-init-parity/vmlinuz-7.1.3-sp11-baseline1+ root=UUID=33e842b7-0434-4749-b03a-299bdcdb8b9f ro clk_ignore_unused pd_ignore_unused cma=128M efi=noruntime quiet splash console=tty0 crashkernel=2G-4G:320M,4G-32G:512M,32G-64G:1024M,64G-128G:2048M,128G-:4096M sp11_entry=7.1.3-phase84-init-parity spi_geni_qcom.sp11_windows_se_init=1 mshw0485_touch.windows_init_parity=1 mshw0485_touch.parity_display_bitmap=1 mshw0485_touch.parity_stitching_flag=0 mshw0485_touch.parity_hinge_angle=400 mshw0485_touch.parity_fast_host_id=400 mshw0485_touch.parity_report56_identity=0xbc,0xe6,0x4a,0x2e,0x86,0x78 mshw0485_touch.parity_report56_flag=0
        initrd /boot/sp11-7.1.3-phase84-init-parity/initrd.img-7.1.3-sp11-baseline1+-phase84
}
