#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
exec tail -n +4 $0
# Phase 85 extends the input-disabled Phase 84 checkpoint through the exact
# installed CFU inventory/no-update branch. It still stops before Heat/input.

menuentry 'Ubuntu SP11 7.1.3 Windows Init + CFU Parity, No Touch (Phase 85)' --id 'sp11-phase85-cfu-parity' --class ubuntu --class gnu-linux --class gnu --class os {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_gpt
        insmod ext2
        insmod fdt
        search --no-floppy --fs-uuid --set=root 33e842b7-0434-4749-b03a-299bdcdb8b9f
        devicetree /boot/sp11-7.1.3-phase85-cfu-parity/x1e80100-microsoft-denali-sp11-phase75.dtb
        linux /boot/sp11-7.1.3-phase85-cfu-parity/vmlinuz-7.1.3-sp11-baseline1+ root=UUID=33e842b7-0434-4749-b03a-299bdcdb8b9f ro clk_ignore_unused pd_ignore_unused cma=128M efi=noruntime quiet splash console=tty0 crashkernel=2G-4G:320M,4G-32G:512M,32G-64G:1024M,64G-128G:2048M,128G-:4096M sp11_entry=7.1.3-phase85-cfu-parity mshw0485_touch.windows_init_parity=1 mshw0485_touch.parity_display_bitmap=1 mshw0485_touch.parity_stitching_flag=0 mshw0485_touch.parity_hinge_angle=400 mshw0485_touch.parity_fast_host_id=400 mshw0485_touch.parity_report56_identity=0xbc,0xe6,0x4a,0x2e,0x86,0x78 mshw0485_touch.parity_report56_flag=0 mshw0485_touch.parity_cfu_inventory=1 mshw0485_touch.parity_cfu_offer=0x00,0x00,0x12,0x00,0x89,0x14,0x00,0x3f,0xff,0xff,0xff,0xff,0x04,0x04,0x75,0x00
        initrd /boot/sp11-7.1.3-phase85-cfu-parity/initrd.img-7.1.3-sp11-baseline1+-phase85
}
