#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0
"""Generate the Q20.12 project-0x0c83 kernel profile from an operator DLL."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

if __package__:
    from tools.extract_windows_classifier import FIXED_ONE, ProjectClassifier
else:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from tools.extract_windows_classifier import FIXED_ONE, ProjectClassifier


def values(name: str, items: list[int], indent: str = "\t") -> list[str]:
    lines = [f"{indent}.{name} = {{"]
    for start in range(0, len(items), 10):
        chunk = ", ".join(str(value) for value in items[start : start + 10])
        lines.append(f"{indent}\t{chunk},")
    lines.append(f"{indent}}},")
    return lines


def generate(dll: bytes, project_id: int) -> str:
    classifier = ProjectClassifier.from_dll(dll, project_id)
    lines = [
        "/* SPDX-License-Identifier: GPL-2.0 */",
        "/* Generated by tools/generate_classifier_header.py; do not edit. */",
        "#ifndef _G6TS_CLASSIFIER_PROFILE_H",
        "#define _G6TS_CLASSIFIER_PROFILE_H",
        "",
        "#define G6TS_CLASS_COUNT 4U",
        "#define G6TS_FEATURE_COUNT 10U",
        "#define G6TS_CLASSIFIER_SHIFT 12U",
        "",
        "struct g6ts_classifier_model {",
        "\tu16 max_points;",
        "\ts32 score_offset_q12;",
        "\ts32 means_q12[G6TS_FEATURE_COUNT];",
        "\ts32 transform_q12[G6TS_FEATURE_COUNT][G6TS_FEATURE_COUNT];",
        "};",
        "",
        "static const struct g6ts_classifier_model g6ts_classifier_models[] = {",
    ]
    for model in classifier.models:
        lines.extend(
            [
                "\t{",
                f"\t\t.max_points = {model.max_points},",
                "\t\t.score_offset_q12 = "
                f"{round((model.decisions[0] - model.bias * 0.5) * FIXED_ONE)},",
            ]
        )
        lines.extend(
            values(
                "means_q12",
                [round(value * FIXED_ONE) for value in model.means],
                "\t\t",
            )
        )
        lines.append("\t\t.transform_q12 = {")
        for row in model.transform:
            encoded = ", ".join(str(round(value * FIXED_ONE)) for value in row)
            lines.append(f"\t\t\t{{ {encoded} }},")
        lines.extend(["\t\t},", "\t},"])
    lines.extend(["};", "", "#endif /* _G6TS_CLASSIFIER_PROFILE_H */", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("dll", type=Path)
    parser.add_argument("--project", type=lambda value: int(value, 0), default=0x0C83)
    args = parser.parse_args()
    print(generate(args.dll.read_bytes(), args.project), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
