#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0
"""Generate the bounded project-0x0c83 kernel lifecycle profile."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

if __package__:
    from tools.extract_windows_classifier import FIXED_ONE, ProjectClassifier
    from tools.extract_windows_lifecycle import ProjectLifecycle
    from tools.windows_tracking_geometry import AssignmentScaleInputs
else:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from tools.extract_windows_classifier import FIXED_ONE, ProjectClassifier
    from tools.extract_windows_lifecycle import ProjectLifecycle
    from tools.windows_tracking_geometry import AssignmentScaleInputs


def _vector(values: tuple[int, ...]) -> str:
    return "{ " + ", ".join(str(value) for value in values) + " }"


def generate(dll: bytes, project_id: int) -> str:
    classifier = ProjectClassifier.from_dll(dll, project_id)
    lifecycle = ProjectLifecycle.from_dll(dll, project_id)
    x_scale, y_scale = AssignmentScaleInputs.from_dll(dll, project_id).scales()
    q24 = FIXED_ONE * FIXED_ONE
    lines = [
        "/* SPDX-License-Identifier: GPL-2.0 */",
        "/* Generated by tools/generate_lifecycle_header.py; do not edit. */",
        "#ifndef _G6TS_LIFECYCLE_PROFILE_H",
        "#define _G6TS_LIFECYCLE_PROFILE_H",
        "",
        "#define G6TS_WINDOWS_UNCLASSIFIED 4U",
        "#define G6TS_WINDOWS_HISTORY_CAPACITY 10U",
        "#define G6TS_WINDOWS_SCORE_SHIFT 24U",
        f"#define G6TS_WINDOWS_RUNTIME_OFFSET_Q24 {round(classifier.runtime_offset * q24)}LL",
        f"#define G6TS_WINDOWS_SCORE3_PRIMARY_Q24 {round(classifier.primary_score3_penalty * q24)}LL",
        f"#define G6TS_WINDOWS_SCORE3_SINGLE_Q24 {round(classifier.single_group_score3_penalty * q24)}LL",
        f"#define G6TS_WINDOWS_ASSIGN_X_SCALE_Q24 {round(x_scale * (1 << 24))}U",
        f"#define G6TS_WINDOWS_ASSIGN_Y_SCALE_Q24 {round(y_scale * (1 << 24))}U",
        f"#define G6TS_WINDOWS_ASSIGN_RADIUS {round(lifecycle.normal_match_radius)}U",
        "",
        "struct g6ts_transition_rule {",
        "\ts32 history_margins[G6TS_CLASS_COUNT];",
        "\ts32 current_margins[G6TS_CLASS_COUNT];",
        "\ts16 absolute_minimum;",
        "\ts8 context_score_bias;",
        "\tu8 history_depth;",
        "\tu8 initial_age_limit;",
        "\tu8 context_allowed;",
        "\tu8 context_extra_history;",
        "};",
        "",
        "static const u16 g6ts_class_point_minimums[G6TS_CLASS_COUNT] =",
        f"\t{_vector(lifecycle.class_point_count_minimums)};",
        "static const u16 g6ts_class_point_maximums[G6TS_CLASS_COUNT] =",
        f"\t{_vector(lifecycle.class_point_count_maximums)};",
        "",
        "static const struct g6ts_transition_rule g6ts_transition_rules[] = {",
    ]
    for rule in lifecycle.rules:
        lines.extend(
            [
                f"\t/* {rule.old_class} -> {rule.new_class} */",
                "\t{",
                f"\t\t.history_margins = {_vector(rule.history_score_margins)},",
                f"\t\t.current_margins = {_vector(rule.current_score_margins)},",
                f"\t\t.absolute_minimum = {rule.absolute_score_min},",
                f"\t\t.context_score_bias = {rule.context_score_bias},",
                f"\t\t.history_depth = {rule.history_depth},",
                f"\t\t.initial_age_limit = {rule.initial_age_limit},",
                f"\t\t.context_allowed = {int(rule.context_allowed)},",
                f"\t\t.context_extra_history = {rule.context_extra_history},",
                "\t},",
            ]
        )
    lines.extend(
        [
            "};",
            "",
            "#endif /* _G6TS_LIFECYCLE_PROFILE_H */",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("dll", type=Path)
    parser.add_argument("--project", type=lambda value: int(value, 0), default=0x0C83)
    parser.add_argument(
        "--check",
        type=Path,
        help="verify that an existing generated header is byte-for-byte current",
    )
    args = parser.parse_args()
    output = generate(args.dll.read_bytes(), args.project)
    if args.check is not None:
        try:
            current = args.check.read_text(encoding="utf-8")
        except OSError as error:
            parser.error(f"cannot read generated header: {error}")
        if current != output:
            print(f"out of date: {args.check}", file=sys.stderr)
            return 1
        print(f"current: {args.check}")
        return 0
    print(output, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
