ccflags-y += -I$(src)/include
ccflags-y += -include linux/types.h
ccflags-y += -include $(src)/include/linux/dma/qcom-gpi-dma.h
ccflags-y += -include $(src)/include/dt-bindings/dma/qcom-gpi.h

obj-m += gpi.o
obj-m += spi-geni-qcom.o
obj-m += g6ts_biosref.o
